apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruby-deployment
  labels:
    app: ruby-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ruby-app
  template:
    metadata:
      labels:
        app: ruby-app
    spec:
      containers:
      - name: ruby-container
        image: "${DOCKER_IMAGE}"   # This will be replaced with actual image name
        ports:
        - containerPort: 4567
