apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruby-deployment
  labels:
    app: ruby-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ruby-app
  template:
    metadata:
      labels:
        app: ruby-app
    spec:
      containers:
      - name: ruby-container
        image: "harikrishh/demo:v1.${BUILD_ID}"  # Jenkins will replace ${BUILD_ID} with the actual value
        ports:
        - containerPort: 4567
